name: Deploy Dev to GitHub Pages

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          
      - name: Deploy to gh-pages branch (dev folder)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: dev
          keep_files: true
          exclude_assets: '.github,*.md'